### ISSUE TITLE
Sass error with node-sass

### ISSUE THREAD

**Issue by mknabe** [kristoferjoseph/flexboxgrid#113]
I'm using node-sass and I'm getting this error when I try to compile.

```
Message:
    property "#{if($i == 0, $iterator-selector, #{$iterator-selector}#{$modifier-delimiter}#{$i}" must be followed by a ':'
Details:
    fileName: /Users/mknabe/dev/buckle/blc-ecom-apps/site/src/main/webapp/WEB-INF/default-theme/bower_components/flexboxgrid/src/sass/flexboxgrid.scss
    lineNumber: 72
```

Any help would be greatly appreciated!
