### ISSUE TITLE
bootstrap and flexboxgrid

### ISSUE THREAD

**Issue by ifokeev** [kristoferjoseph/flexboxgrid#134]
If you are using flexboxgrid with bootstrap 3.x.x, you can catch the bug (I got it in Safari): 

![the bug](https://cldup.com/LyBtW_8Fi6.png)

I have 4 ```.col-md-3``` cols and they don't fit the container.
 
It appears because of:

```css
.row:before, .row:after {
    content: " ";   // <----- this line
    display: table;
}
```

the ```flex-basis``` of this empty space is 1px, so you should redefine it:

```css
.row:before, .row:after {
  flex-basis: 0;
  order: 1;
}
```

I spent a lot of time resolving this issue, maybe it will be useful for you.
