### ISSUE TITLE
Add text-align fallback for IE Edge

### ISSUE THREAD

**Issue by reskir** [kristoferjoseph/flexboxgrid#146]
Flexbox text-align property start, end doesn't work in IE and Edge browsers. Instead for fallback it should be defined text-align: left; right.

https://davidwalsh.name/text-align-start

**Comment by kristoferjoseph** [comment]
Thanks for the info! I changed the name of the issue to make it an actionable item.

**Comment by inakianduaga** [comment]
Adding the following css before flexboxgrid makes it work on IE11

```css
/**
 * Text-align fallback for older browsers
 */
.start-xs {
    text-align: left;
}

.end-xs {
    text-align: right;
}

@media only screen and (min-width: 48em) {

    .start-sm {
        text-align: left;
    }

    .end-sm {
        text-align: right;
    }

}

@media only screen and (min-width: 64em) {

    .start-md {
        text-align: left;
    }

    .end-md {
        text-align: right;
    }
}

@media only screen and (min-width: 75em) {

    .start-lg {
        text-align: left;
    }

    .end-lg {
        text-align: right;
    }

}
```

This needs to be merged into the regular build
