### ISSUE TITLE
How to set gutter, margin and breakpoins to my needs?

### ISSUE THREAD

**Issue by andrealopezmora** [kristoferjoseph/flexboxgrid#241]
### Briefly ( tweet size ) describe your issue and how you discovered it.

I need to set gutter, margins and breakpoints to other values, what's the best way to achieve that?
Thanks.

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce behavior

* OS:
* Browser:
* code/fiddle/pen url:

**Comment by baj84** [comment]
+1

**Comment by jan-dh** [comment]
+1

**Comment by jan-dh** [comment]
Actually, this is quiet easy:

**Gutter**

You can find adjust the gutter by changing the following:

`
$gutter: 30px;
.row{
  margin-right:-$gutter/2;
}`

**Comment by CruelMoney** [comment]
@jan-dh what css file are you referring to?

**Comment by dockwarder** [comment]
@jan-dh How do you set the padding for all the col-x elements? If I'm not totally wrong, then you need to select all col-(xs|sm|md|lg) elements and re-set the padding and do all that again for each new breakpoint.

**Comment by xeaone** [comment]
@jan-dh You got us pointed in the right direction but the `|` is  "equal to or starts with". Which work if you always start with flexbox classes so I think the following is in improvement.

```css
.row {
  margin-left: 0;
  margin-right: 0;
}
[class~="col"]:not([class*="offset"]),
[class*="col-"]:not([class*="offset"]) {
  padding-left: 0;
  padding-right: 0;
}
```
