### ISSUE TITLE
Conflict with bootstrap

### ISSUE THREAD

**Issue by cyrilchapon** [kristoferjoseph/flexboxgrid#245]
The way elements are declared (eg: `.container`, `.col-sx-12`) conflict with bootstrap.

While it's understanding that one aims to *replace* bootstrap grid system, and almost works (except some opiniated choices, like `rem` usage, and except some people - many people - tweak bootstrap using LESS or SASS, and this completely breaks things with this module...), classes could be declared, maybe, with `...-flex-...` or something, to allow both works together.

**Comment by supra28** [comment]
I don't understand the use case of using this along with bootstrap if you don't intend on replacing bootstrap's grid system.

**Comment by cyrilchapon** [comment]
Exactly, the fact you can't anticipate each use-case one will attempt to cover with a library is presicely the point to make it avoid conflict.

**Comment by kristoferjoseph** [comment]
it is not meant to be used with bootstrap. 
if you use boostrap then use the supplied grid... or don't

**Comment by gremo** [comment]
Using LESS, this library works very well without conflicts (just nest inside `.flexboxgrid`):

```less
.flexboxgrid {
  @import (less) "../../../web/components/flexboxgrid/dist/flexboxgrid.css";

  .container-fluid,
  .container {
    padding-left:  (@grid-gutter-width / 2);
    padding-right: (@grid-gutter-width / 2);
  }

  .container {
    @media (min-width: @screen-sm-min) { width: @container-sm; }
    @media (min-width: @screen-md-min) { width: @container-md; }
    @media (min-width: @screen-lg-min) { width: @container-lg; }
  }

  .row {
    &:before,
    &:after { content: none; }

    margin-left:  (@grid-gutter-width / -2);
    margin-right: (@grid-gutter-width / -2);
  }

  [class^="col-"],
  [class*=" col-"] {
    padding-left:  (@grid-gutter-width / 2);
    padding-right: (@grid-gutter-width / 2);
  }
}
```
