### ISSUE TITLE
Mobile reorder Elements/row/columns  

### ISSUE THREAD

**Issue by shanewmurphy** [kristoferjoseph/flexboxgrid#269]
### Briefly ( tweet size ) describe your issue and how you discovered it.
 @kristoferjoseph  Having used this Flexgrid system in my project I wish to reorder elements on mobile & the syntax for doing so is NOT working when using this grid system. Am I correct in saying you can not reorder columns/rows using your grid?  
...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce behavior

* OS:
* Browser:
* code/fiddle/pen url:

**Comment by JohnMica** [comment]
did you try with ? 
``` 
@media all and (max-width: XXXpx) {
    container { 
      order: 1
   }
}
```

**Comment by joeygallegos** [comment]
I accomplished this by using the below code in my environment

```scss
@media only screen and (max-width: 575px),
		screen and (max-width: 768px) {
	.col-first-mobile {
		order: -1;
	}
}
```
