### ISSUE TITLE
How to implement full-width layouts?

### ISSUE THREAD

**Issue by rayshan** [kristoferjoseph/flexboxgrid#78]
If one was to implement this:
http://getbootstrap.com/examples/dashboard/

Making the root element a `row` enables horizontal scrolling due to:
https://github.com/kristoferjoseph/flexboxgrid/blob/master/dist/flexboxgrid.css#L42-L43

Making the root element a `container-fluid` like bootstrap then making the next level a `row` leaves padding space on the sides. 

Any reason for the negative margin on `row`?

**Comment by kristoferjoseph** [comment]
The negative margins on row are to enable rows are to compensate for the gutters. 
Try this and let me know if it solves your issue. http://codepen.io/dam/pen/rajLmx

**Comment by rayshan** [comment]
Yes that works, didn't need to touch body due to using normalize.css. Thanks!

**Comment by kristoferjoseph** [comment]
FYI: I am looking into other ways to do gutters and margins that will not use negative margins.

**Comment by rayshan** [comment]
:tada:

**Comment by zjrosen1** [comment]
+1 for not using negative margin

**Comment by Aybee** [comment]
>  I am looking into other ways to do gutters and margins that will not use negative margins.

I fiddled around with space-between
https://jsfiddle.net/Andreas/zpw3nqvt/

**Comment by kristoferjoseph** [comment]
@aybee nice! That was one approach I was playing with. Only issue is I couldn't set the gutters to a specific width. Good for a lot of cases though.

**Comment by Aybee** [comment]
Yes, in my example `calc(33.333% - 1rem)` gutter width is not exactly 1rem. You can not calculate the exact gutter width for flex-basis as you don't know the number of COLs inside one ROW. 

```css
.col-xs-3 {
  flex-basis: calc(25% - gutter_width / col_count * (col_count - 1));
}
/*
e.g. with 4 COLs of type .col-xs-3 and gutter width of 20px:
25% - 20px / 4 * 3
25% - 15px
*/
```
And doing it with first- and last-child will lead to expensive CSS code.

```css
.col-xs-3 {
  flex-basis: calc(25% - 20px);
}
.col-xs-3:first-child,
.col-xs-3:last-child {
  flex-basis: calc(25% - 10px);
}
.col-xs-6 {
  flex-basis: calc(50% - 20px);
}
.col-xs-6:first-child,
.col-xs-6:last-child {
  flex-basis: calc(50% - 10px);
}
```

Also using calc() can lead to problems, see here http://caniuse.com/#feat=calc

So you can do it with border or padding, as box-sizing already is set. But then you have to do the formating on the children of the COLs and not on the COLs themselve.

Another way is to use space-around instead space-between but then you will have a left and a right space.
