### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by nnnnic** [kristoferjoseph/flexboxgrid#9]
Would love the ability to align column contents with specific classes, such as:

``` CSS
.right {
    text-align: right;
}
```

Did it manually for now and it's fandamntastic.

<3 u.
