### ISSUE TITLE
Remove paddings

### ISSUE THREAD

**Issue by visualcookie** [kristoferjoseph/flexboxgrid#99]
Hi,

I want to remove paddings on the column classes. Tried to do it with this tiny snip:
``` sass
.work {
   line-height: 0;
   padding-left: 0;
   padding-right: 0;
   margin: 0;
}
```

Didn't worked somehow. There's a large gap at the end.

**Comment by kristoferjoseph** [comment]
Do add the `.container` class around your grid this should fix the isssue. The padding is needed to compensate for gutters when the rows wrap. The container class was added in a PR so that flexboxgrid mapped more directly to the bootstrap grid implementation.

**Comment by visualcookie** [comment]
@kristoferjoseph Thanks. Did work. :+1:

**Comment by visualcookie** [comment]
Hi, just checked it again... and on fullscreen getting the same issue again. Here's a pen of what I want to achieve (see "Wanted Behavior").

http://codepen.io/visualcookie/full/qdYwvE/

**Comment by mileandra** [comment]
Works fine for me when giving container-fluid and the columns a padding of 0px. In what browser are you seeing the issues?

**Comment by kristoferjoseph** [comment]
Me too. Any more info?

**Comment by kristoferjoseph** [comment]
#101 Will fix this.

**Comment by visualcookie** [comment]
@kristoferjoseph Method that worked for me now:

``` scss
.container {
   max-width: 980px;
}

[class*='col-'],
[class^='col-'] {
   img {
      max-width: 100%;
      height: auto;
   }
}

.row--no-gutter {
   margin-left: 0;
   margin-right: 0;
}

.col--no-gutter {
   padding-left: 0;
   padding-right: 0;
}
```

Plus, as you can see, I declared my own container with a max-width and removed yours from the mixins. Don't need to have a "fixed" em width, when only one declaration works. :)
